(deftheme wu)

(custom-theme-set-faces
 'wu
 '(default ((t (:family "Fira Code" :background "#121212" :foreground "#cdba96"))))
 '(font-lock-comment-face ((t (:foreground "#7a8b8b"))))
 '(highlight ((t (:background "#4a708b"))))
 '(region ((t (:background "#cdb7b5"))))
 '(font-lock-string-face ((t (:foreground "#4FAA79" :weight normal))))
 '(font-lock-keyword-face ((t (:foreground "#9AB77C" :weight normal))))
 '(font-lock-function-name-face ((t (:foreground "#ffb5c5" :weight normal))))
 '(font-lock-comment-face ((t (:foreground "DarkSeaGreen4" :weight normal))))
 '(font-lock-doc-face ((t (:foreground "dark cyan" :weight normal))))
 '(font-lock-constant-face ((t (:foreground "#cd919e" :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "#8b795e" :weight normal))))
 '(font-lock-type-face ((t (:foreground "#96cdcd" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "light sea green" :weight normal))))
 '(org-level-1 ((t (:foreground "#c1cdcd" :weight bold))))
 '(org-level-2 ((t (:foreground "#8b8378"))))
 ;; company
 '(company-preview ((t (:foreground "darkgray" :underline t))))
 '(company-preview-common ((t (:inherit company-preview))))
 '(company-tooltip ((t (:background "lightgray" :foreground "black"))))
 '(company-tooltip-selection ((t (:background "steelblue" :foreground "white"))))
 '(company-tooltip-common ((((type x)) (:inherit company-tooltip :weight bold))
                           (t (:inherit company-tooltip))))
 '(company-tooltip-common-selection ((((type x)) (:inherit company-tooltip-selection :weight bold))
                                     (t (:inherit company-tooltip-selection))))
 '(company-scrollbar-bg ((t (:background "#121212"))))
 '(company-scrollbar-fg ((t (:background "#121212"))))
 '(eldoc-highlight-function-argument ((t (:inherit bold :foreground "#00ee76" :underline t :weight bold))))
)

(provide-theme 'wu)

